### ISSUE TITLE
feat: Analysis Whether Facts are Known to Other Contract Party

### ISSUE THREAD

**Issue by MartinKoelbl** [sen-uni-kn/ContractCheck#2]
### Description
A contract party that does not know a concrete fact (e.g. financial report), will not fulfill a claim resulting from this fact.

### Task
- [ ] Implement an analysis that finds unkown facts inconsistencies
- [ ] notate fact/claims on which a claim depend (which is difference to Trigger)
- [ ] before/after dependency analysis

### Definition of Done
- The implemented analysis will find the inconsistency in the long contract.
