### ISSUE TITLE
Legal Action Simulator

### ISSUE THREAD

**Issue by MartinKoelbl** [sen-uni-kn/ContractCheck#31]
### Description
The current analyses compute single executions, starting at the signing of the contract until the full performance. A user is interested in a contract analysis during the execution of a contract. For instance, a contracting party can call for a claim only in certain time ranges (e.g. a subsequent claim because of a missing handover is not possible before the handover was due). 

### Goals
- [ ] Compute an execution until a certain date (with respect to a given set of legal facts / actions)
- [ ] An analysis that computes the possible actions on a certain date
- [ ] Compute possible future result ranges (e.g. range of possible purchase price)
- [x] Show possible actions in WebInterface
