### ISSUE TITLE
bug: Z3 Output Red Warnings Because of Soft Assert

### ISSUE THREAD

**Issue by MartinKoelbl** [sen-uni-kn/ContractCheck#4]
### Description
Z3 outputs red warnings for the generated Z3 models with soft asserts.

### Tasks
- [ ] change implementation to remove red warnings
- [ ] check whether Z3 analysis computes correct models

### Definition of Done
- [ ] No output of red warnings
